# CI module for PyDCC
#
# Copyright (c) Siemens AG, 2021
#
# Authors:
#  Andreas Tobola <andreas.tobola@siemens.com>
#
# This work is licensed under the terms of the MIT License. 
# See the LICENSEle in the top-level directory.
#

# https://hub.docker.com/r/library/python/tags/
image: "python:3.7" 

before_script:
  - python --version
#  - pip install pylint
  - pip install -e .

stages:
#  - Static Analysis
  - Unit Tests
  - Version Increment

#pylint:
#  stage: Static Analysis
#  script:
#  - pylint src/*.py

test:
  stage: Unit Tests
  script:
  - cd tests
  - python unit_test.py

vincr:
  stage: Version Increment
  script:
  - python increase_version.py
