# CI module for PyDCC
#
# Copyright (c) Siemens AG, 2021
#
# Authors:
#  Andreas Tobola <andreas.tobola@siemens.com>
#
# This work is licensed under the terms of the MIT License. 
# See the LICENSEle in the top-level directory.
#

# https://hub.docker.com/r/library/python/tags/
image: "python:3.8" 

before_script:
  - python --version
#  - pip install pylint

stages:
#  - Static Analysis
  - Unit Tests
  - Doc Check
#  - Version Increment

#pylint:
#  stage: Static Analysis
#  script:
#  - pylint src/*.py

test:
  stage: Unit Tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
  - pip install -e .  
  - pip install pytest
  - pip install pytest-cov
  - cd tests
  - pytest --cov=dcc -cov-branch --cov-report term-missing 

doc:
  stage: Doc Check
  script:
  - pip install -e . 
  - cd tests
  - python documentation_check.py

#vincr:
#  stage: Version Increment
#  script:
#  - python increase_version.py
